Fancybox.bind();
import { workflowMeasurements } from "./scripts/workflowMeasurements";
workflowMeasurements();
import { rightSideMenu } from "./scripts/rightSideMenu";
rightSideMenu();
import { burgerMenu } from "./scripts/burgerMenu";
burgerMenu();
import { slickSliderSettings } from "./scripts/slickSliderSettings";
slickSliderSettings();
import { mixitupSettings } from "./scripts/mixitupSettings";
mixitupSettings();
